const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Sin,
		C3.Behaviors.Persist,
		C3.Behaviors.Fade,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Behaviors.destroy,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.Orbit,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Tilemap,
		C3.Plugins.Particles,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.FileSystem,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Spritefont2.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.LocalStorage.Cnds.OnItemSet,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Spritefont2.Acts.TypewriterFinish,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Audio.Exps.PlaybackRate,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Orbit.Acts.SetEnabled,
		C3.Plugins.FileSystem.Acts.AddAcceptType,
		C3.Plugins.FileSystem.Acts.ShowSaveFilePicker,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.FileSystem.Cnds.OnPickerComplete,
		C3.Plugins.FileSystem.Acts.WriteTextFile,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.Tilemap.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.System.Cnds.OnSaveComplete,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.EightDir.Acts.SetDefaultControls,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.SetEffectEnabled,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToBottom
	];
};
self.C3_JsPropNameTable = [
	{DialogueStage: 0},
	{Flash: 0},
	{MoveTo: 0},
	{Sine: 0},
	{Blub: 0},
	{Blueberry: 0},
	{CandyKnight: 0},
	{CandyNPC: 0},
	{CandyNPC2: 0},
	{CandyNPC3: 0},
	{CribNPC: 0},
	{CribNPC2: 0},
	{Persist: 0},
	{Dozer: 0},
	{Elyssa: 0},
	{Fade: 0},
	{glormbus: 0},
	{Huxley: 0},
	{KhiliPepper: 0},
	{Kiosk: 0},
	{Lolipop: 0},
	{Mallium: 0},
	{Polaris: 0},
	{Squirt: 0},
	{Waiter: 0},
	{Warden: 0},
	{WcDonaldsNPC: 0},
	{WcDonaldsNPC2: 0},
	{Wilson: 0},
	{BudgetFrog: 0},
	{Physics: 0},
	{Solid: 0},
	{DestroyOutsideLayout: 0},
	{Pin: 0},
	{ElyssaPlush: 0},
	{CribPlush: 0},
	{CribNPC3: 0},
	{CribNPC4: 0},
	{CribNPC5: 0},
	{Fiveshadow: 0},
	{secretnpc: 0},
	{secretnpc2: 0},
	{MenuTXT: 0},
	{PRESSZTOSTART: 0},
	{Logo: 0},
	{IntroTXT: 0},
	{WhiteFade: 0},
	{TextBox: 0},
	{DialogueTXT: 0},
	{BlackFade: 0},
	{Z: 0},
	{Black: 0},
	{PortraitBox: 0},
	{DialogueTXT2: 0},
	{charPortrait: 0},
	{TextBox3: 0},
	{l: 0},
	{ArcadeGreen: 0},
	{ArcadeGreen2: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{AlliumPlayer: 0},
	{AlliumBattle: 0},
	{MipArcade: 0},
	{PlayerTurretArcade: 0},
	{BattleBKG: 0},
	{BattleBKG2: 0},
	{MHPBarBKG: 0},
	{MHPBar: 0},
	{BattleTXT: 0},
	{MHPCount: 0},
	{EnemyHPBarBKG: 0},
	{EnemyHPBar: 0},
	{EnemyHeart: 0},
	{HP: 0},
	{Orbit: 0},
	{EnemyBarrier: 0},
	{Bullet: 0},
	{EnemyBullet: 0},
	{EnemyTurret: 0},
	{PlayerTurret: 0},
	{PlayerBullet: 0},
	{BlackFadeBattle: 0},
	{EnemyBullet2: 0},
	{EnemyBullet3: 0},
	{EnemyBullet4: 0},
	{EnemyBullet5: 0},
	{EnemyBullet6: 0},
	{ArcadeBullet: 0},
	{ArcadeEnemyBullet: 0},
	{HighCount: 0},
	{PlayerTurretEcho: 0},
	{ArcadeParryBullet: 0},
	{BattleSpotlight: 0},
	{EnemyBullet7: 0},
	{Aimer: 0},
	{EnemyBullet7Echo: 0},
	{EnemyBullet8: 0},
	{EnemyHeart2: 0},
	{EnemyBullet9: 0},
	{AkumuBattleSpotlight: 0},
	{PongPointCount: 0},
	{PlayerPong: 0},
	{EnemyPong: 0},
	{PongBullet: 0},
	{pointforplayer: 0},
	{pointforenemy: 0},
	{EnemyHeart3: 0},
	{TurArrowUp: 0},
	{TurArrowDown: 0},
	{TurArrowRight: 0},
	{TurArrowLeft: 0},
	{EnemyBullet10: 0},
	{EnemyBullet11: 0},
	{EnemyBullet12: 0},
	{EnemyBullet13: 0},
	{BattleTXT2: 0},
	{EnemyBullet14: 0},
	{PongBullet2: 0},
	{greenshield: 0},
	{EnemyBullet15: 0},
	{Aimer2: 0},
	{Sine2: 0},
	{AkumuBattleSpotlight2: 0},
	{EnemyBullet16: 0},
	{TurArrowDown2: 0},
	{TurArrowLeft2: 0},
	{TurArrowRight2: 0},
	{TurArrowUp2: 0},
	{EnemyBullet17: 0},
	{SAVEHER_Bullet1: 0},
	{SAVEHER_Heal1: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Door: 0},
	{Trigger: 0},
	{Border: 0},
	{Tilemap: 0},
	{Warp: 0},
	{sweetSand: 0},
	{feathers: 0},
	{FurryWorldBKG: 0},
	{AlliumPic: 0},
	{huxleyparticles: 0},
	{Particles: 0},
	{centerbox: 0},
	{darkspotlight: 0},
	{darkgradient: 0},
	{arcade: 0},
	{REDDEATH: 0},
	{deltaexplosion: 0},
	{ElyssaRoomBKG: 0},
	{catbed: 0},
	{PingPongTable: 0},
	{PingPongBKG: 0},
	{CafeteriaTables: 0},
	{MessHallTable: 0},
	{toaster: 0},
	{evildeathbattle: 0},
	{deadcloversigilbook: 0},
	{holeinwall: 0},
	{holeinwall2: 0},
	{tallgrass: 0},
	{LaserLine: 0},
	{trashcan: 0},
	{toilet: 0},
	{LaserLine2: 0},
	{Particles2: 0},
	{knive: 0},
	{furryPillars: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Warp2: 0},
	{candygridbkg: 0},
	{correct: 0},
	{disappear: 0},
	{clicked: 0},
	{CandyObj: 0},
	{Touch: 0},
	{Warp3: 0},
	{Warp4: 0},
	{castledistance: 0},
	{clouds: 0},
	{TiledBackground: 0},
	{floatingislands: 0},
	{cassettePickup: 0},
	{FileSystem: 0},
	{BurgerBun: 0},
	{BurgerBottom: 0},
	{tomato: 0},
	{lettuce: 0},
	{ketchup: 0},
	{burgerpatty: 0},
	{cheeseburg: 0},
	{ketchup2: 0},
	{Boombox: 0},
	{EVADECover: 0},
	{ClawMachineBox: 0},
	{BorderPhysics: 0},
	{MachineClaw: 0},
	{ClawX: 0},
	{ClawY: 0},
	{HorizontalSine: 0},
	{VerticalSine: 0},
	{PuzzleClaw: 0},
	{PuzzleClaw2: 0},
	{TicTacSquare: 0},
	{BattleBarrier: 0},
	{FurryTile: 0},
	{ResetButton: 0},
	{SpikeBarriers: 0},
	{FurryPaintings: 0},
	{FurryCreatorBKG: 0},
	{FurryCreatorBKG2: 0},
	{theone: 0},
	{animationNo: 0},
	{FurryHead: 0},
	{FurryBody: 0},
	{FurryLegs: 0},
	{FurryTile2: 0},
	{PolarisBattleBackground: 0},
	{PolarisBattleBKG: 0},
	{REDDEATHEVIL: 0},
	{MLG: 0},
	{CarnivalGameOverlay: 0},
	{CarnivalAimer: 0},
	{CarnivalDuck: 0},
	{puffParticles: 0},
	{WardenBKG: 0},
	{StaticSine: 0},
	{SAVEHER: 0},
	{SAVEHERBKG: 0},
	{SAVEHERHands: 0},
	{SAVEHER_Laser: 0},
	{Spooky: 0},
	{puzzleZone: 0},
	{policespotlight: 0},
	{concreteroad: 0},
	{noise: 0},
	{mastervolume: 0},
	{GameOverQuote: 0},
	{Playtime: 0},
	{CurrVolNum: 0},
	{Speedrun: 0},
	{BoomboxSelect: 0},
	{gotCutesyExe: 0},
	{gotLonelyPiano: 0},
	{gotBrokenRecord: 0},
	{gotSAVEHER: 0},
	{gotFrogSong: 0},
	{gotEVADE: 0},
	{GameOverQuote2: 0},
	{AsylumCutsceneFinalDone: 0},
	{LetSAVEPressZ: 0},
	{LetNPCPressZ1: 0},
	{LetNPCPressZ2: 0},
	{LetNPCPressZ3: 0},
	{SAVEDialogueStage: 0},
	{NPCDialogueStage: 0},
	{ElyssaCutsceneDone: 0},
	{WarpCooldown: 0},
	{LolipopCutsceneDone: 0},
	{HuxleyCutsceneDone: 0},
	{KnightCutsceneDone: 0},
	{KnightCutsceneDone2: 0},
	{GlormbusCutsceneDone: 0},
	{LolipopBattleCutsceneDone: 0},
	{CandyPuzzleCutsceneDone: 0},
	{correctSelected: 0},
	{incorrectSelected: 0},
	{CandyPuzzleCutsceneDone2: 0},
	{correctSelected2: 0},
	{incorrectSelected2: 0},
	{CandyPuzzleCutsceneDone3: 0},
	{correctSelected3: 0},
	{incorrectSelected3: 0},
	{CarnivalCutsceneDone: 0},
	{CarnivalCutsceneDone2: 0},
	{carnivalPts: 0},
	{CarnivalTimeLeft: 0},
	{CarnivalCutsceneDone3: 0},
	{CribCutsceneDone5: 0},
	{CribCutsceneDone6: 0},
	{CribCutsceneDone7: 0},
	{CribCutsceneDone: 0},
	{CribCutsceneDone2: 0},
	{CribCutsceneDone3: 0},
	{CribCutsceneDone4: 0},
	{TicTacKey: 0},
	{ElyssaCutsceneClaw: 0},
	{TicTacCutsceneDone: 0},
	{MovementAllow: 0},
	{CutsceneDialogueStage: 0},
	{CutsceneLetPressZ: 0},
	{DVCutscene1Done: 0},
	{DVCutscene2Done: 0},
	{triggeredDV2: 0},
	{AlliumX: 0},
	{AlliumY: 0},
	{DVCutscene3Done: 0},
	{DVCutscene4Done: 0},
	{GotAngelTear: 0},
	{FurryWorldCutsceneDone: 0},
	{FurryWorldCutsceneDone2: 0},
	{FurryWorldCutsceneDone3: 0},
	{FurryWorldCutsceneDone4: 0},
	{FurryOCCreatorDone: 0},
	{FurryHeadSelected: 0},
	{FurryBodySelected: 0},
	{FurryLegSelected: 0},
	{FurryOCCreatorDone2: 0},
	{sadHuxCutsceneDone: 0},
	{gotMindKey: 0},
	{budgetFrogCassetteClue2: 0},
	{WcDonaldsCutsceneDone5: 0},
	{WcDonaldsCutsceneDone6: 0},
	{WcDonaldsCutsceneDone: 0},
	{WcDonaldsCutsceneDone2: 0},
	{WcDonaldsPuzzleDone: 0},
	{WcDonaldsCutsceneDone3: 0},
	{WcDonaldsCutsceneDone4: 0},
	{BurgerPoints: 0},
	{budgetFrogCassetteClue: 0},
	{PrevLayout: 0},
	{battleTalk: 0},
	{MHP: 0},
	{EnemyMHP: 0},
	{MAXEnemyMHP: 0},
	{BattlePhase: 0},
	{BattleDialogueStage: 0},
	{RecoverBuildup: 0},
	{MaxMHP: 0}
];

self.InstanceType = {
	Blub: class extends self.ISpriteInstance {},
	Blueberry: class extends self.ISpriteInstance {},
	CandyKnight: class extends self.ISpriteInstance {},
	CandyNPC: class extends self.ISpriteInstance {},
	CandyNPC2: class extends self.ISpriteInstance {},
	CandyNPC3: class extends self.ISpriteInstance {},
	CribNPC: class extends self.ISpriteInstance {},
	CribNPC2: class extends self.ISpriteInstance {},
	Dozer: class extends self.ISpriteInstance {},
	Elyssa: class extends self.ISpriteInstance {},
	glormbus: class extends self.ISpriteInstance {},
	Huxley: class extends self.ISpriteInstance {},
	KhiliPepper: class extends self.ISpriteInstance {},
	Kiosk: class extends self.ISpriteInstance {},
	Lolipop: class extends self.ISpriteInstance {},
	Mallium: class extends self.ISpriteInstance {},
	Polaris: class extends self.ISpriteInstance {},
	Squirt: class extends self.ISpriteInstance {},
	Waiter: class extends self.ISpriteInstance {},
	Warden: class extends self.ISpriteInstance {},
	WcDonaldsNPC: class extends self.ISpriteInstance {},
	WcDonaldsNPC2: class extends self.ISpriteInstance {},
	Wilson: class extends self.ISpriteInstance {},
	BudgetFrog: class extends self.ISpriteInstance {},
	ElyssaPlush: class extends self.ISpriteInstance {},
	CribPlush: class extends self.ISpriteInstance {},
	CribNPC3: class extends self.ISpriteInstance {},
	CribNPC4: class extends self.ISpriteInstance {},
	CribNPC5: class extends self.ISpriteInstance {},
	Fiveshadow: class extends self.ISpriteInstance {},
	secretnpc: class extends self.ISpriteInstance {},
	secretnpc2: class extends self.ISpriteInstance {},
	MenuTXT: class extends self.ISpriteFontInstance {},
	PRESSZTOSTART: class extends self.ISpriteFontInstance {},
	Logo: class extends self.ISpriteInstance {},
	IntroTXT: class extends self.ISpriteFontInstance {},
	WhiteFade: class extends self.ISpriteInstance {},
	TextBox: class extends self.ISpriteInstance {},
	DialogueTXT: class extends self.ISpriteFontInstance {},
	BlackFade: class extends self.ISpriteInstance {},
	Z: class extends self.ISpriteFontInstance {},
	Black: class extends self.ISpriteInstance {},
	PortraitBox: class extends self.ISpriteInstance {},
	DialogueTXT2: class extends self.ISpriteFontInstance {},
	charPortrait: class extends self.ISpriteInstance {},
	TextBox3: class extends self.ISpriteInstance {},
	l: class extends self.ISpriteInstance {},
	ArcadeGreen: class extends self.ISpriteInstance {},
	ArcadeGreen2: class extends self.ISpriteInstance {},
	AlliumPlayer: class extends self.ISpriteInstance {},
	AlliumBattle: class extends self.ISpriteInstance {},
	MipArcade: class extends self.ISpriteInstance {},
	PlayerTurretArcade: class extends self.ISpriteInstance {},
	BattleBKG: class extends self.ITiledBackgroundInstance {},
	BattleBKG2: class extends self.ITiledBackgroundInstance {},
	MHPBarBKG: class extends self.ISpriteInstance {},
	MHPBar: class extends self.ISpriteInstance {},
	BattleTXT: class extends self.ISpriteFontInstance {},
	MHPCount: class extends self.ISpriteFontInstance {},
	EnemyHPBarBKG: class extends self.ISpriteInstance {},
	EnemyHPBar: class extends self.ISpriteInstance {},
	EnemyHeart: class extends self.ISpriteInstance {},
	EnemyBarrier: class extends self.ISpriteInstance {},
	EnemyBullet: class extends self.ISpriteInstance {},
	EnemyTurret: class extends self.ISpriteInstance {},
	PlayerTurret: class extends self.ISpriteInstance {},
	PlayerBullet: class extends self.ISpriteInstance {},
	BlackFadeBattle: class extends self.ISpriteInstance {},
	EnemyBullet2: class extends self.ISpriteInstance {},
	EnemyBullet3: class extends self.ISpriteInstance {},
	EnemyBullet4: class extends self.ISpriteInstance {},
	EnemyBullet5: class extends self.ISpriteInstance {},
	EnemyBullet6: class extends self.ISpriteInstance {},
	ArcadeBullet: class extends self.ISpriteInstance {},
	ArcadeEnemyBullet: class extends self.ISpriteInstance {},
	HighCount: class extends self.ISpriteFontInstance {},
	PlayerTurretEcho: class extends self.ISpriteInstance {},
	ArcadeParryBullet: class extends self.ISpriteInstance {},
	BattleSpotlight: class extends self.ISpriteInstance {},
	EnemyBullet7: class extends self.ISpriteInstance {},
	Aimer: class extends self.ISpriteInstance {},
	EnemyBullet7Echo: class extends self.ISpriteInstance {},
	EnemyBullet8: class extends self.ISpriteInstance {},
	EnemyHeart2: class extends self.ISpriteInstance {},
	EnemyBullet9: class extends self.ISpriteInstance {},
	AkumuBattleSpotlight: class extends self.ISpriteInstance {},
	PongPointCount: class extends self.ISpriteFontInstance {},
	PlayerPong: class extends self.ISpriteInstance {},
	EnemyPong: class extends self.ISpriteInstance {},
	PongBullet: class extends self.ISpriteInstance {},
	pointforplayer: class extends self.ISpriteInstance {},
	pointforenemy: class extends self.ISpriteInstance {},
	EnemyHeart3: class extends self.ISpriteInstance {},
	TurArrowUp: class extends self.ISpriteInstance {},
	TurArrowDown: class extends self.ISpriteInstance {},
	TurArrowRight: class extends self.ISpriteInstance {},
	TurArrowLeft: class extends self.ISpriteInstance {},
	EnemyBullet10: class extends self.ISpriteInstance {},
	EnemyBullet11: class extends self.ISpriteInstance {},
	EnemyBullet12: class extends self.ISpriteInstance {},
	EnemyBullet13: class extends self.ISpriteInstance {},
	BattleTXT2: class extends self.ISpriteFontInstance {},
	EnemyBullet14: class extends self.ISpriteInstance {},
	PongBullet2: class extends self.ISpriteInstance {},
	greenshield: class extends self.ISpriteInstance {},
	EnemyBullet15: class extends self.ISpriteInstance {},
	Aimer2: class extends self.ISpriteInstance {},
	AkumuBattleSpotlight2: class extends self.ISpriteInstance {},
	EnemyBullet16: class extends self.ISpriteInstance {},
	TurArrowDown2: class extends self.ISpriteInstance {},
	TurArrowLeft2: class extends self.ISpriteInstance {},
	TurArrowRight2: class extends self.ISpriteInstance {},
	TurArrowUp2: class extends self.ISpriteInstance {},
	EnemyBullet17: class extends self.ISpriteInstance {},
	SAVEHER_Bullet1: class extends self.ISpriteInstance {},
	SAVEHER_Heal1: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Door: class extends self.ISpriteInstance {},
	Trigger: class extends self.ISpriteInstance {},
	Border: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Warp: class extends self.ISpriteInstance {},
	sweetSand: class extends self.IParticlesInstance {},
	feathers: class extends self.IParticlesInstance {},
	FurryWorldBKG: class extends self.ISpriteInstance {},
	AlliumPic: class extends self.ISpriteInstance {},
	huxleyparticles: class extends self.IParticlesInstance {},
	Particles: class extends self.IParticlesInstance {},
	centerbox: class extends self.ISpriteInstance {},
	darkspotlight: class extends self.ISpriteInstance {},
	darkgradient: class extends self.ISpriteInstance {},
	arcade: class extends self.ISpriteInstance {},
	REDDEATH: class extends self.ISpriteInstance {},
	deltaexplosion: class extends self.ISpriteInstance {},
	ElyssaRoomBKG: class extends self.ISpriteInstance {},
	catbed: class extends self.ISpriteInstance {},
	PingPongTable: class extends self.ISpriteInstance {},
	PingPongBKG: class extends self.ISpriteInstance {},
	CafeteriaTables: class extends self.ISpriteInstance {},
	MessHallTable: class extends self.ISpriteInstance {},
	toaster: class extends self.ISpriteInstance {},
	evildeathbattle: class extends self.ISpriteInstance {},
	deadcloversigilbook: class extends self.ISpriteInstance {},
	holeinwall: class extends self.ISpriteInstance {},
	holeinwall2: class extends self.ISpriteInstance {},
	tallgrass: class extends self.ISpriteInstance {},
	LaserLine: class extends self.ISpriteInstance {},
	trashcan: class extends self.ISpriteInstance {},
	toilet: class extends self.ISpriteInstance {},
	LaserLine2: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	knive: class extends self.ISpriteInstance {},
	furryPillars: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Warp2: class extends self.ISpriteInstance {},
	candygridbkg: class extends self.ISpriteInstance {},
	CandyObj: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Warp3: class extends self.ISpriteInstance {},
	Warp4: class extends self.ISpriteInstance {},
	castledistance: class extends self.ISpriteInstance {},
	clouds: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	floatingislands: class extends self.ISpriteInstance {},
	cassettePickup: class extends self.ISpriteInstance {},
	FileSystem: class extends self.IInstance {},
	BurgerBun: class extends self.ISpriteInstance {},
	BurgerBottom: class extends self.ISpriteInstance {},
	tomato: class extends self.ISpriteInstance {},
	lettuce: class extends self.ISpriteInstance {},
	ketchup: class extends self.ISpriteInstance {},
	burgerpatty: class extends self.ISpriteInstance {},
	cheeseburg: class extends self.ISpriteInstance {},
	ketchup2: class extends self.ISpriteInstance {},
	Boombox: class extends self.ISpriteInstance {},
	EVADECover: class extends self.ISpriteInstance {},
	ClawMachineBox: class extends self.ISpriteInstance {},
	BorderPhysics: class extends self.ISpriteInstance {},
	MachineClaw: class extends self.ISpriteInstance {},
	PuzzleClaw: class extends self.ISpriteInstance {},
	PuzzleClaw2: class extends self.ISpriteInstance {},
	TicTacSquare: class extends self.ISpriteInstance {},
	BattleBarrier: class extends self.ISpriteInstance {},
	FurryTile: class extends self.ISpriteInstance {},
	ResetButton: class extends self.ISpriteInstance {},
	SpikeBarriers: class extends self.ISpriteInstance {},
	FurryPaintings: class extends self.ISpriteInstance {},
	FurryCreatorBKG: class extends self.ISpriteInstance {},
	FurryCreatorBKG2: class extends self.ISpriteInstance {},
	FurryHead: class extends self.ISpriteInstance {},
	FurryBody: class extends self.ISpriteInstance {},
	FurryLegs: class extends self.ISpriteInstance {},
	FurryTile2: class extends self.ISpriteInstance {},
	PolarisBattleBackground: class extends self.ISpriteInstance {},
	PolarisBattleBKG: class extends self.ITiledBackgroundInstance {},
	REDDEATHEVIL: class extends self.ISpriteInstance {},
	MLG: class extends self.ISpriteInstance {},
	CarnivalGameOverlay: class extends self.ISpriteInstance {},
	CarnivalAimer: class extends self.ISpriteInstance {},
	CarnivalDuck: class extends self.ISpriteInstance {},
	puffParticles: class extends self.IParticlesInstance {},
	WardenBKG: class extends self.ITiledBackgroundInstance {},
	SAVEHER: class extends self.ISpriteInstance {},
	SAVEHERBKG: class extends self.ISpriteInstance {},
	SAVEHERHands: class extends self.ISpriteInstance {},
	SAVEHER_Laser: class extends self.ISpriteInstance {},
	Spooky: class extends self.ISpriteInstance {},
	puzzleZone: class extends self.ISpriteInstance {},
	policespotlight: class extends self.ISpriteInstance {},
	concreteroad: class extends self.ITiledBackgroundInstance {}
}